/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTransfersRouteImport } from './routes/_app.transfers'
import { Route as AppTrainingRouteImport } from './routes/_app.training'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSubscriptionsRouteImport } from './routes/_app.subscriptions'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRecruitmentRouteImport } from './routes/_app.recruitment'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLeaveRouteImport } from './routes/_app.leave'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppContractsRouteImport } from './routes/_app.contracts'
import { Route as AppCompaniesRouteImport } from './routes/_app.companies'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAccountingRouteImport } from './routes/_app.accounting'
import { Route as AppTransfersBatchIdRouteImport } from './routes/_app.transfers.$batchId'
import { Route as AppPayrollRunIdRouteImport } from './routes/_app.payroll.$runId'
import { Route as AppEmployeesEmployeeIdRouteImport } from './routes/_app.employees.$employeeId'
import { Route as AppContractsContractIdRouteImport } from './routes/_app.contracts.$contractId'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app.companies.$companyId'
import { Route as AppPayrollPayslipPayslipIdRouteImport } from './routes/_app.payroll.payslip.$payslipId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentRoute = AppRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersBatchIdRoute = AppTransfersBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => AppTransfersRoute,
} as any)
const AppPayrollRunIdRoute = AppPayrollRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AppPayrollRoute,
} as any)
const AppEmployeesEmployeeIdRoute = AppEmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppContractsContractIdRoute = AppContractsContractIdRouteImport.update({
  id: '/$contractId',
  path: '/$contractId',
  getParentRoute: () => AppContractsRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => AppCompaniesRoute,
} as any)
const AppPayrollPayslipPayslipIdRoute =
  AppPayrollPayslipPayslipIdRouteImport.update({
    id: '/payslip/$payslipId',
    path: '/payslip/$payslipId',
    getParentRoute: () => AppPayrollRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/accounting': typeof AppAccountingRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/assets': typeof AppAssetsRoute
  '/attendance': typeof AppAttendanceRoute
  '/companies': typeof AppCompaniesRouteWithChildren
  '/contracts': typeof AppContractsRouteWithChildren
  '/documents': typeof AppDocumentsRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/leave': typeof AppLeaveRoute
  '/notifications': typeof AppNotificationsRoute
  '/payroll': typeof AppPayrollRouteWithChildren
  '/performance': typeof AppPerformanceRoute
  '/recruitment': typeof AppRecruitmentRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/tasks': typeof AppTasksRoute
  '/training': typeof AppTrainingRoute
  '/transfers': typeof AppTransfersRouteWithChildren
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/contracts/$contractId': typeof AppContractsContractIdRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/payroll/$runId': typeof AppPayrollRunIdRoute
  '/transfers/$batchId': typeof AppTransfersBatchIdRoute
  '/payroll/payslip/$payslipId': typeof AppPayrollPayslipPayslipIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/accounting': typeof AppAccountingRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/assets': typeof AppAssetsRoute
  '/attendance': typeof AppAttendanceRoute
  '/companies': typeof AppCompaniesRouteWithChildren
  '/contracts': typeof AppContractsRouteWithChildren
  '/documents': typeof AppDocumentsRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/leave': typeof AppLeaveRoute
  '/notifications': typeof AppNotificationsRoute
  '/payroll': typeof AppPayrollRouteWithChildren
  '/performance': typeof AppPerformanceRoute
  '/recruitment': typeof AppRecruitmentRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/tasks': typeof AppTasksRoute
  '/training': typeof AppTrainingRoute
  '/transfers': typeof AppTransfersRouteWithChildren
  '/': typeof AppIndexRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/contracts/$contractId': typeof AppContractsContractIdRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/payroll/$runId': typeof AppPayrollRunIdRoute
  '/transfers/$batchId': typeof AppTransfersBatchIdRoute
  '/payroll/payslip/$payslipId': typeof AppPayrollPayslipPayslipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/companies': typeof AppCompaniesRouteWithChildren
  '/_app/contracts': typeof AppContractsRouteWithChildren
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/leave': typeof AppLeaveRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/payroll': typeof AppPayrollRouteWithChildren
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/recruitment': typeof AppRecruitmentRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscriptions': typeof AppSubscriptionsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/training': typeof AppTrainingRoute
  '/_app/transfers': typeof AppTransfersRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/contracts/$contractId': typeof AppContractsContractIdRoute
  '/_app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/_app/payroll/$runId': typeof AppPayrollRunIdRoute
  '/_app/transfers/$batchId': typeof AppTransfersBatchIdRoute
  '/_app/payroll/payslip/$payslipId': typeof AppPayrollPayslipPayslipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/accounting'
    | '/admin'
    | '/ai'
    | '/assets'
    | '/attendance'
    | '/companies'
    | '/contracts'
    | '/documents'
    | '/employees'
    | '/leave'
    | '/notifications'
    | '/payroll'
    | '/performance'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/tasks'
    | '/training'
    | '/transfers'
    | '/companies/$companyId'
    | '/contracts/$contractId'
    | '/employees/$employeeId'
    | '/payroll/$runId'
    | '/transfers/$batchId'
    | '/payroll/payslip/$payslipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/accounting'
    | '/admin'
    | '/ai'
    | '/assets'
    | '/attendance'
    | '/companies'
    | '/contracts'
    | '/documents'
    | '/employees'
    | '/leave'
    | '/notifications'
    | '/payroll'
    | '/performance'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/tasks'
    | '/training'
    | '/transfers'
    | '/'
    | '/companies/$companyId'
    | '/contracts/$contractId'
    | '/employees/$employeeId'
    | '/payroll/$runId'
    | '/transfers/$batchId'
    | '/payroll/payslip/$payslipId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/accounting'
    | '/_app/admin'
    | '/_app/ai'
    | '/_app/assets'
    | '/_app/attendance'
    | '/_app/companies'
    | '/_app/contracts'
    | '/_app/documents'
    | '/_app/employees'
    | '/_app/leave'
    | '/_app/notifications'
    | '/_app/payroll'
    | '/_app/performance'
    | '/_app/recruitment'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/subscriptions'
    | '/_app/tasks'
    | '/_app/training'
    | '/_app/transfers'
    | '/_app/'
    | '/_app/companies/$companyId'
    | '/_app/contracts/$contractId'
    | '/_app/employees/$employeeId'
    | '/_app/payroll/$runId'
    | '/_app/transfers/$batchId'
    | '/_app/payroll/payslip/$payslipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/training': {
      id: '/_app/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment': {
      id: '/_app/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AppRecruitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave': {
      id: '/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts': {
      id: '/_app/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers/$batchId': {
      id: '/_app/transfers/$batchId'
      path: '/$batchId'
      fullPath: '/transfers/$batchId'
      preLoaderRoute: typeof AppTransfersBatchIdRouteImport
      parentRoute: typeof AppTransfersRoute
    }
    '/_app/payroll/$runId': {
      id: '/_app/payroll/$runId'
      path: '/$runId'
      fullPath: '/payroll/$runId'
      preLoaderRoute: typeof AppPayrollRunIdRouteImport
      parentRoute: typeof AppPayrollRoute
    }
    '/_app/employees/$employeeId': {
      id: '/_app/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/contracts/$contractId': {
      id: '/_app/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof AppContractsContractIdRouteImport
      parentRoute: typeof AppContractsRoute
    }
    '/_app/companies/$companyId': {
      id: '/_app/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/_app/payroll/payslip/$payslipId': {
      id: '/_app/payroll/payslip/$payslipId'
      path: '/payslip/$payslipId'
      fullPath: '/payroll/payslip/$payslipId'
      preLoaderRoute: typeof AppPayrollPayslipPayslipIdRouteImport
      parentRoute: typeof AppPayrollRoute
    }
  }
}

interface AppCompaniesRouteChildren {
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
}

const AppCompaniesRouteChildren: AppCompaniesRouteChildren = {
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
}

const AppCompaniesRouteWithChildren = AppCompaniesRoute._addFileChildren(
  AppCompaniesRouteChildren,
)

interface AppContractsRouteChildren {
  AppContractsContractIdRoute: typeof AppContractsContractIdRoute
}

const AppContractsRouteChildren: AppContractsRouteChildren = {
  AppContractsContractIdRoute: AppContractsContractIdRoute,
}

const AppContractsRouteWithChildren = AppContractsRoute._addFileChildren(
  AppContractsRouteChildren,
)

interface AppEmployeesRouteChildren {
  AppEmployeesEmployeeIdRoute: typeof AppEmployeesEmployeeIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesEmployeeIdRoute: AppEmployeesEmployeeIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppPayrollRouteChildren {
  AppPayrollRunIdRoute: typeof AppPayrollRunIdRoute
  AppPayrollPayslipPayslipIdRoute: typeof AppPayrollPayslipPayslipIdRoute
}

const AppPayrollRouteChildren: AppPayrollRouteChildren = {
  AppPayrollRunIdRoute: AppPayrollRunIdRoute,
  AppPayrollPayslipPayslipIdRoute: AppPayrollPayslipPayslipIdRoute,
}

const AppPayrollRouteWithChildren = AppPayrollRoute._addFileChildren(
  AppPayrollRouteChildren,
)

interface AppTransfersRouteChildren {
  AppTransfersBatchIdRoute: typeof AppTransfersBatchIdRoute
}

const AppTransfersRouteChildren: AppTransfersRouteChildren = {
  AppTransfersBatchIdRoute: AppTransfersBatchIdRoute,
}

const AppTransfersRouteWithChildren = AppTransfersRoute._addFileChildren(
  AppTransfersRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCompaniesRoute: typeof AppCompaniesRouteWithChildren
  AppContractsRoute: typeof AppContractsRouteWithChildren
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppLeaveRoute: typeof AppLeaveRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPayrollRoute: typeof AppPayrollRouteWithChildren
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppRecruitmentRoute: typeof AppRecruitmentRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppTransfersRoute: typeof AppTransfersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCompaniesRoute: AppCompaniesRouteWithChildren,
  AppContractsRoute: AppContractsRouteWithChildren,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppLeaveRoute: AppLeaveRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPayrollRoute: AppPayrollRouteWithChildren,
  AppPerformanceRoute: AppPerformanceRoute,
  AppRecruitmentRoute: AppRecruitmentRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppTransfersRoute: AppTransfersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
